function test_packet_schedule
%TEST_PACKET_SCHEDULE Validate the fair 256-bit/256-symbol packet design.

repoRoot = fileparts(fileparts(mfilename('fullpath')));
htPath = fullfile(repoRoot, '802.11nHT');
addpath(htPath);
cleanup = onCleanup(@() rmpath(htPath));

[~, bits222, schedule222] = vmscatterBuildPacketSchedule(2, 128, 4);
[~, bits244, schedule244] = vmscatterBuildPacketSchedule(4, 64, 4);

assert(numel(bits222) == 256 && numel(bits244) == 256, ...
    'Both architectures must carry 256 tag bits per packet.');
assert(schedule222.numDataSymbols == 256 && ...
    schedule244.numDataSymbols == 256, ...
    'Both architectures must use 256 data OFDM symbols.');
assert(schedule222.numReferenceSymbols == 4, ...
    '2x2x2 must use one explicit state times four repeats.');
assert(schedule244.numReferenceSymbols == 12, ...
    '2x4x4 must use three explicit states times four repeats.');
assert(rank(schedule222.designStateMatrix) == 2 && ...
    rank(schedule244.designStateMatrix) == 4, ...
    'The LTF baseline plus explicit references must be full rank.');
assert(schedule222.numExplicitReferenceStates == 1 && ...
    schedule244.numExplicitReferenceStates == 3, ...
    'The explicit reference count must be K-1.');

[states222, bitsHT222, scheduleHT222] = vmscatterBuildPacketSchedule( ...
    2, 128, 4, 'Mode', 'HighThroughput');
[states244, bitsHT244, scheduleHT244] = vmscatterBuildPacketSchedule( ...
    4, 128, 4, 'Mode', 'HighThroughput');
assert(numel(bitsHT222) == 256 && numel(bitsHT244) == 512, ...
    'High-throughput packets must carry K bits per 8-us tag slot.');
assert(scheduleHT222.numDataSymbols == 256 && ...
    scheduleHT244.numDataSymbols == 256, ...
    'High-throughput comparisons must use 256 data OFDM symbols.');
assert(scheduleHT222.rawBitsPerDataSymbol == 1 && ...
    scheduleHT244.rawBitsPerDataSymbol == 2);
assert(size(states222, 2) == 260 && size(states244, 2) == 268, ...
    'Reference and data symbol counts are inconsistent.');

allBits2 = dec2bin(0:3, 2) - '0';
expectedStates2 = [1 1; -1 1; -1 -1; 1 -1];
assert(isequal(vmscatterHighThroughputMap(allBits2), expectedStates2), ...
    'The two-antenna mapping must match paper Fig. 4.');
allBits4 = dec2bin(0:15, 4) - '0';
states4 = vmscatterHighThroughputMap(allBits4);
assert(size(unique(states4, 'rows'), 1) == 16, ...
    'The four-antenna pairwise extension must be bijective.');
end
