function summaries = test_ht_packet_noiseless(numPackets)
%TEST_HT_PACKET_NOISELESS Validate many-codeword 222 and 244 packets.

if nargin < 1
    numPackets = 100;
end
repoRoot = fileparts(fileparts(mfilename('fullpath')));
htPath = fullfile(repoRoot, '802.11nHT');
addpath(htPath);
cleanup = onCleanup(@() rmpath(htPath));

summaries = table;
for repeats = [1 2 4]
    summaries = [summaries; ...
        runArchitecture(2, 2, 128, repeats, numPackets); ...
        runArchitecture(4, 4, 64, repeats, numPackets)]; %#ok<AGROW>
end
assert(all(summaries.BitErrors == 0), ...
    'A noiseless packet-level tag BER is not zero.');
assert(all(summaries.DecodeFailures == 0), ...
    'A noiseless packet-level decode failed.');
end

function summary = runArchitecture( ...
    numTag, numRx, numCodewords, referenceRepeats, numPackets)
rng(3000 + numTag, 'twister');
cfgHT = wlanHTConfig( ...
    'ChannelBandwidth', 'CBW20', ...
    'NumTransmitAntennas', 2, ...
    'NumSpaceTimeStreams', 2, ...
    'PSDULength', 2000, ...
    'MCS', 8, ...
    'ChannelCoding', 'BCC', ...
    'SpatialMapping', 'Direct');
sampleRate = wlanSampleRate(cfgHT);
preChannel = makeChannel(2, numTag, sampleRate);
postChannel = makeChannel(numTag, numRx, sampleRate);
fieldIndices = wlanFieldIndices(cfgHT);
bitErrors = 0;
decodeFailures = 0;

for packetIndex = 1:numPackets
    reset(preChannel);
    reset(postChannel);
    txPSDU = randi([0 1], cfgHT.PSDULength * 8, 1);
    tx = wlanWaveformGenerator(txPSDU, cfgHT, 'WindowTransitionTime', 0);
    txSC = vmscatterHTDataSubcarriers(tx, cfgHT);
    preTagWaveform = preChannel([tx; zeros(64, 2)]);
    [taggedWaveform, txTagBits, schedule] = VMscatterModPacket( ...
        preTagWaveform, fieldIndices, numTag, cfgHT, ...
        'NumCodewords', numCodewords, ...
        'ReferenceRepeats', referenceRepeats);
    rx = postChannel(taggedWaveform);
    [~, rxStreams, detectionError, rxDiagnostics] = rxDemod(rx, cfgHT);
    if detectionError
        bitErrors = bitErrors + numel(txTagBits);
        decodeFailures = decodeFailures + 1;
        continue;
    end
    [rxTagBits, success] = VMscatterDeModPacket( ...
        txSC, vmscatterHTStreamsToAntennas(rxStreams, cfgHT), ...
        schedule, cfgHT, ...
        'SubcarrierWeights', rxDiagnostics.dataSubcarrierReliability);
    if success
        bitErrors = bitErrors + sum(txTagBits(:) ~= rxTagBits(:));
    else
        bitErrors = bitErrors + numel(txTagBits);
        decodeFailures = decodeFailures + 1;
    end
end

summary = table(string(sprintf('2x%dx%d', numTag, numRx)), ...
    referenceRepeats, numPackets, bitErrors, decodeFailures, ...
    'VariableNames', {'Architecture', 'ReferenceRepeats', 'Packets', ...
    'BitErrors', 'DecodeFailures'});
end

function channel = makeChannel(numTx, numRx, sampleRate)
channel = wlanTGnChannel( ...
    'DelayProfile', 'Model-A', ...
    'NumTransmitAntennas', numTx, ...
    'NumReceiveAntennas', numRx, ...
    'EnvironmentalSpeed', 0, ...
    'LargeScaleFadingEffect', 'None', ...
    'NormalizeChannelOutputs', false, ...
    'SampleRate', sampleRate, ...
    'RandomStream', 'Global stream');
end
