function result = run_all_reference_profiles(varargin)
%RUN_ALL_REFERENCE_PROFILES Compare Minimal, Default, and Robust profiles.

parser = inputParser;
addParameter(parser, 'SNR', 2:10, @(x) isnumeric(x) && isvector(x));
addParameter(parser, 'MinBits', 1e5, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 256);
addParameter(parser, 'MaxBits', 2e6, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 256);
addParameter(parser, 'TargetErrors', 200, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(parser, 'Seed', 2020, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x));
addParameter(parser, 'Mode', 'LowBER', ...
    @(x) any(strcmpi(string(x), ["LowBER", "HighThroughput"])));
addParameter(parser, 'NumDataSymbols', 256, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1 && fix(x) == x);
addParameter(parser, 'Plot', true, @(x) islogical(x) && isscalar(x));
addParameter(parser, 'SaveResults', true, ...
    @(x) islogical(x) && isscalar(x));
addParameter(parser, 'OutputDirectory', '', ...
    @(x) ischar(x) || (isstring(x) && isscalar(x)));
parse(parser, varargin{:});
options = parser.Results;

versionRoot = fileparts(fileparts(mfilename('fullpath')));
outputDirectory = string(options.OutputDirectory);
if strlength(outputDirectory) == 0
    outputDirectory = fullfile(versionRoot, 'results');
end

profiles = ["Minimal"; "Default"; "Robust"];
reports = cell(numel(profiles), 1);
for index = 1:numel(profiles)
    reports{index} = run_reference_profile_comparison( ...
        'Profile', profiles(index), ...
        'SNR', options.SNR, ...
        'MinBits', options.MinBits, ...
        'MaxBits', options.MaxBits, ...
        'TargetErrors', options.TargetErrors, ...
        'Seed', options.Seed, ...
        'Mode', options.Mode, ...
        'NumDataSymbols', options.NumDataSymbols, ...
        'Plot', options.Plot, ...
        'SaveResults', options.SaveResults, ...
        'OutputDirectory', outputDirectory);
end

reference222 = cellfun(@(x) x.explicitReferences222, reports);
reference244 = cellfun(@(x) x.explicitReferences244, reports);
strictWins = cellfun(@(x) x.consecutiveStrictWins244, reports);
rawBERWins = cellfun(@(x) sum( ...
    x.results244.ConditionalBER < x.results222.ConditionalBER), reports);
slope222 = cellfun(@(x) x.diversitySlope222, reports);
slope244 = cellfun(@(x) x.diversitySlope244, reports);
goodputGain244 = cellfun(@(x) x.meanGoodputGain244, reports);
success = cellfun(@(x) x.successCriterion, reports);
modeColumn = repmat(string(validatestring(options.Mode, ...
    {'LowBER', 'HighThroughput'})), numel(profiles), 1);
summary = table(modeColumn, profiles, reference222, reference244, ...
    rawBERWins, strictWins, ...
    slope222, slope244, goodputGain244, success, ...
    'VariableNames', {'Mode', 'Profile', 'ExplicitReferences222', ...
    'ExplicitReferences244', 'SNRPointsWithLowerBER244', ...
    'ConsecutiveStrictWins244', ...
    'DiversitySlope222', 'DiversitySlope244', ...
    'MeanGoodputGain244', 'Success'});

result = struct('reports', {reports}, 'summary', summary, ...
    'successfulProfiles', profiles(success), ...
    'anyProfileSucceeded', any(success), 'settings', options);

if options.SaveResults
    if ~exist(outputDirectory, 'dir')
        mkdir(outputDirectory);
    end
    modeStem = lower(char(modeColumn(1)));
    writetable(summary, fullfile(outputDirectory, ...
        ['profile_summary_' modeStem '.csv']));
    save(fullfile(outputDirectory, ['all_profiles_' modeStem '.mat']), 'result');
end
end
