function [taggedWaveform, tagBits, schedule] = VMscatterModPacket( ...
    waveform, ind, numTag, cfgHT, varargin)
%VMSCATTERMODPACKET Apply one reference block and many tag codewords.

vmscatterValidateHTConfig(cfgHT, numTag);
validateattributes(waveform, {'double'}, {'2d', 'finite', 'nonempty'}, ...
    mfilename, 'waveform');
if size(waveform, 2) ~= numTag
    error('VMScatter:InvalidTagInput', ...
        'The pre-tag waveform must have one column per tag antenna.');
end

parser = inputParser;
addParameter(parser, 'NumCodewords', 1, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1 && fix(x) == x);
addParameter(parser, 'ReferenceRepeats', 1, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1 && fix(x) == x);
addParameter(parser, 'TagBits', [], @(x) isempty(x) || isnumeric(x));
addParameter(parser, 'ReferenceRefreshCodewords', Inf, ...
    @(x) isnumeric(x) && isscalar(x) && ...
    (isinf(x) || (x >= 1 && fix(x) == x)));
addParameter(parser, 'Mode', 'LowBER', ...
    @(x) any(strcmpi(x, {'LowBER', 'HighThroughput'})));
parse(parser, varargin{:});

[tagStates, tagBits, schedule] = vmscatterBuildPacketSchedule( ...
    numTag, parser.Results.NumCodewords, parser.Results.ReferenceRepeats, ...
    'TagBits', parser.Results.TagBits, ...
    'ReferenceRefreshCodewords', parser.Results.ReferenceRefreshCodewords, ...
    'Mode', parser.Results.Mode);

info = wlanHTOFDMInfo('HT-Data', cfgHT);
symbolLength = info.FFTLength + info.CPLength;
requiredEnd = ind.HTData(1) + schedule.numSymbols * symbolLength - 1;
if size(waveform, 1) < requiredEnd
    availableSymbols = floor((size(waveform, 1) - ind.HTData(1) + 1) / symbolLength);
    error('VMScatter:InsufficientHTSymbols', ...
        ['VMScatter schedule needs %d HT-Data symbols, but the packet ' ...
        'contains only %d complete symbols.'], ...
        schedule.numSymbols, availableSymbols);
end

taggedWaveform = waveform;
for symbolIndex = 1:schedule.numSymbols
    firstSample = ind.HTData(1) + symbolLength * (symbolIndex - 1);
    lastSample = firstSample + symbolLength - 1;
    taggedWaveform(firstSample:lastSample, :) = ...
        taggedWaveform(firstSample:lastSample, :) * ...
        diag(tagStates(:, symbolIndex));
end
schedule.tagStates = tagStates;
end
